version: '3'

services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=$CLOUDFLARE_TUNNEL_TOKEN
    volumes:
      - $CONFIG_ROOT/cloudflared:/etc/cloudflared
    networks:
      - server_default

networks:
  server_default:
    external: true
    name: server_default
