version: '3'

networks:
  media-server:
    external: true

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - $CONFIG_ROOT/plex:/config
      - $CONFIG_ROOT/plex/transcoding:/data/transcode
      - $MOVIES:/data/movies
      - $SHOWS:/data/tv
    ports:
      - 32400:32400
    restart: unless-stopped
    environment:
      - VERSION=docker
      - TZ=$TZ
      - PLEX_CLAIM=$PLEX_CLAIM
    networks:
      - media-server
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - transmission
    volumes:
      - $CONFIG_ROOT/sonarr:/config
      - $DOWNLOADS:/downloads
      - $SHOWS:/tv
    environment:
      - TZ=$TZ
    networks:
      - media-server
    ports:
      - 8989:8989
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
      - transmission
    volumes:
      - $CONFIG_ROOT/radarr:/config
      - $DOWNLOADS:/downloads
      - $MOVIES:/movies
    environment:
      - TZ=$TZ
    networks:
      - media-server
    ports:
      - 7878:7878
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=$TZ
    ports:
      - 5055:5055
    volumes:
      - $CONFIG_ROOT/overseerr:/app/config
    networks:
      - media-server
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - AUTO_UPDATE=true
      - RUN_OPTS=
    volumes:
      - $CONFIG_ROOT/jackett:/config
      - $CONFIG_ROOT/jackett/downloads:/downloads
    networks:
      - media-server
    ports:
      - 9117:9117
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - TRANSMISSION_WEB_HOME=
      - USER=$TRANSMISSION_USER
      - PASS=$TRANSMISSION_PASS
      - WHITELIST=
      - PEERPORT=
      - HOST_WHITELIST=
    volumes:
      - $CONFIG_ROOT/transmission:/config
      - $CONFIG_ROOT/transmission/watch:/watch
      - $DOWNLOADS:/downloads
    networks:
      - media-server
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
