version: '3.9'

networks:
  mynetwork:
    external:
      name: $DOCKER_NETWORK

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - $CONFIG_ROOT/jellyfin:/config
      - $SHOWS:/data/tvshows
      - $MOVIES:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      - mynetwork
    devices:
     - "/dev/dri:/dev/dri" # Intel QSV

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=$TZ
    ports:
      - 5055:5055
    volumes:
      - $CONFIG_ROOT/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - mynetwork

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - $CONFIG_ROOT/sonarr:/config
      - $DOWNLOADS:/downloads
      - $SHOWS:/tv
    environment:
      - TZ=$TZ
    ports:
      - 8989:8989
    networks:
      - mynetwork

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - $CONFIG_ROOT/radarr:/config
      - $DOWNLOADS:/downloads
      - $MOVIES:/movies
    environment:
      - TZ=$TZ
    ports:
      - 7878:7878
    networks:
      - mynetwork

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - $CONFIG_ROOT/bazarr:/config
      - $MOVIES:/movies
      - $SHOWS:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - mynetwork

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - AUTO_UPDATE=true
      - RUN_OPTS=
    volumes:
      - $CONFIG_ROOT/jackett:/config
      - $CONFIG_ROOT/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - mynetwork

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - TRANSMISSION_WEB_HOME=
      - USER=$TRANSMISSION_USER
      - PASS=$TRANSMISSION_PASS
      - WHITELIST=
      - PEERPORT=
      - HOST_WHITELIST=
    volumes:
      - $CONFIG_ROOT/transmission:/config
      - $CONFIG_ROOT/transmission/watch:/watch
      - $DOWNLOADS:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - mynetwork
