version: '3.9'

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - $CONFIG_ROOT/plex:/config
      - $CONFIG_ROOT/plex/transcoding:/data/transcode
      - $MOVIES:/data/movies
      - $SHOWS:/data/tv
    ports:
      - 32400:32400
    restart: unless-stopped
    environment:
      - VERSION=docker
      - TZ=$TZ
      - PLEX_CLAIM=$PLEX_CLAIM
    networks:
      - server_default
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - transmission
    volumes:
      - $CONFIG_ROOT/sonarr:/config
      - $DOWNLOADS:/downloads
      - $SHOWS:/tv
    environment:
      - TZ=$TZ
    networks:
      - server_default
    ports:
      - 8989:8989
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
      - transmission
    volumes:
      - $CONFIG_ROOT/radarr:/config
      - $DOWNLOADS:/downloads
      - $MOVIES:/movies
    environment:
      - TZ=$TZ
    networks:
      - server_default
    ports:
      - 7878:7878
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - $CONFIG_ROOT/bazarr:/config
      - $MOVIES:/movies
      - $SHOWS:/tv
    networks:
      - server_default
    ports:
      - 6767:6767
    restart: unless-stopped
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=$TZ
    ports:
      - 5055:5055
    volumes:
      - $CONFIG_ROOT/overseerr:/app/config
    networks:
      - server_default
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - AUTO_UPDATE=true
      - RUN_OPTS=
    volumes:
      - $CONFIG_ROOT/jackett:/config
      - $CONFIG_ROOT/jackett/downloads:/downloads
    networks:
      - server_default
    ports:
      - 9117:9117
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - TRANSMISSION_WEB_HOME=
      - USER=$TRANSMISSION_USER
      - PASS=$TRANSMISSION_PASS
      - WHITELIST=
      - PEERPORT=
      - HOST_WHITELIST=
    volumes:
      - $CONFIG_ROOT/transmission:/config
      - $CONFIG_ROOT/transmission/watch:/watch
      - $DOWNLOADS:/downloads
    networks:
      - server_default
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  cloudflare-tunnel:
    image: erisamoe/cloudflared
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run --protocol=http2
    ports:
      - 7844:7844/udp
    environment:
      - TUNNEL_TOKEN=$CLOUDFLARE_TUNNEL_TOKEN
    networks:
      - server_default
    profiles:
      - all
  timemachine:
    image: odarriba/timemachine
    container_name: timemachine
    restart: unless-stopped
    volumes:
      - $TIMEMACHINE_ROOT:/timemachine
    ports:
      - 548:548
      - 636:636
    environment:
      - AFP_SIZE_LIMIT=250000
      - AFP_NAME=Backups
    profiles:
      - all
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - $CONFIG_ROOT/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - server_default
    profiles:
      - all

networks:
  server_default:
    external: true
    name: server_default
